#!/bin/bash

echo "================================"
echo "🔍 Finding the Correct Service Name"
echo "================================"
echo ""

echo "Run these commands on your VPS to find the service:"
echo ""

echo "# 1. List all services with 'saro' or 'smart' in the name:"
echo "sudo systemctl list-units --type=service | grep -i saro"
echo "sudo systemctl list-units --type=service | grep -i smart"
echo "sudo systemctl list-units --type=service | grep -i flask"
echo "sudo systemctl list-units --type=service | grep -i python"
echo ""

echo "# 2. Check all service files in systemd:"
echo "ls -la /etc/systemd/system/*.service | grep -i saro"
echo "ls -la /etc/systemd/system/*.service | grep -i smart"
echo ""

echo "# 3. Check running Python processes:"
echo "ps aux | grep python"
echo "ps aux | grep gunicorn"
echo ""

echo "# 4. Check what's running on port 8001:"
echo "sudo lsof -i :8001"
echo "sudo netstat -tlnp | grep 8001"
echo ""

echo "================================"
echo "Common Service Names:"
echo "================================"
echo "- smartgardenhub.service"
echo "- saro.service"
echo "- flask-app.service"
echo "- school.service"
echo "- gunicorn.service"
echo ""

echo "================================"
echo "Once you find the service name:"
echo "================================"
echo ""
echo "# Replace SERVICE_NAME with the actual name:"
echo "sudo systemctl stop SERVICE_NAME"
echo "pip3 install gunicorn"
echo "cd /var/www/school"
echo "pip3 install -r requirements.txt"
echo "git pull origin main"
echo "sudo systemctl daemon-reload"
echo "sudo systemctl restart SERVICE_NAME"
echo "sudo systemctl status SERVICE_NAME"
echo ""
