#!/bin/bash

echo "================================"
echo "🔍 VPS Service Diagnostic Guide"
echo "================================"
echo ""
echo "Run these commands on your VPS to diagnose the issue:"
echo ""
echo "# 1. Check service status"
echo "sudo systemctl status saro_vps"
echo ""
echo "# 2. View recent logs (last 50 lines)"
echo "sudo journalctl -u saro_vps -n 50 --no-pager"
echo ""
echo "# 3. Check if port 8001 is in use"
echo "sudo lsof -i :8001"
echo ""
echo "# 4. Check if gunicorn is installed"
echo "which gunicorn"
echo "python3 -m pip list | grep gunicorn"
echo ""
echo "# 5. Test if the app can start manually"
echo "cd /var/www/school"
echo "python3 app.py"
echo ""
echo "================================"
echo "⚠️  Common Issues & Fixes:"
echo "================================"
echo ""
echo "Issue 1: Gunicorn not found"
echo "Fix: sudo pip3 install gunicorn"
echo ""
echo "Issue 2: Missing Python dependencies"
echo "Fix: cd /var/www/school && pip3 install -r requirements.txt"
echo ""
echo "Issue 3: Database file permissions"
echo "Fix: sudo chown -R root:root /var/www/school"
echo "     sudo chmod 664 /var/www/school/smartgardenhub.db"
echo ""
echo "Issue 4: Port 8001 already in use"
echo "Fix: sudo lsof -ti:8001 | xargs sudo kill -9"
echo "     sudo systemctl restart saro_vps"
echo ""
echo "Issue 5: Systemd service file not loaded"
echo "Fix: sudo cp /var/www/school/saro_vps.service /etc/systemd/system/"
echo "     sudo systemctl daemon-reload"
echo "     sudo systemctl enable saro_vps"
echo "     sudo systemctl restart saro_vps"
echo ""
echo "================================"
echo "📋 Full Deployment Sequence:"
echo "================================"
echo ""
echo "# On VPS, run these commands in order:"
echo ""
echo "cd /var/www/school"
echo "git pull origin main"
echo ""
echo "# Install/update dependencies"
echo "pip3 install -r requirements.txt"
echo ""
echo "# Copy service file if needed"
echo "sudo cp saro_vps.service /etc/systemd/system/"
echo "sudo systemctl daemon-reload"
echo ""
echo "# Enable and restart service"
echo "sudo systemctl enable saro_vps"
echo "sudo systemctl restart saro_vps"
echo ""
echo "# Check status"
echo "sudo systemctl status saro_vps"
echo ""
echo "# If failed, view full logs"
echo "sudo journalctl -u saro_vps -n 100 --no-pager"
echo ""
echo "================================"
